### ISSUE TITLE
Can you share the script for generating the prior distribution of the token？

### ISSUE THREAD

**Issue by a154377713** [sail-sg/regmix#8]

**Comment by SivilTaram** [comment]
Hello, you can use the following demo code to print the rough prior distribution of different domains (warning: you have to preprocess the dataset using a relatively small chunk so that the number of chunks can represent the tokens, and this code assumes that your domain prefix is separated using `-`):

```python
import os

def get_prefix_tokens(folder_path):
    # read all files in the folder
    all_files = os.listdir(folder_path)
    # shuffle
    random.shuffle(all_files)
    # filter prefix with doremi
    all_files = [file_path for file_path in all_files if "train_" in file_path]
    prefix_dict = {}
    for file_path in all_files:
        # get the prefix
        prefix = file_path.split("-")[0].strip()
        if prefix in prefix_dict:
            prefix_dict[prefix] += 1
        else:
            prefix_dict[prefix] = 1
    # print the normalized weight
    total = sum(prefix_dict.values())
    for prefix in prefix_dict:
        print(prefix + ": ", prefix_dict[prefix]/total)
```

**Comment by aflah02** [comment]
Hi @SivilTaram
Can you explain what do you mean by "(warning: you have to preprocess the dataset using a relatively small chunk size [at here](https://github.com/sail-sg/regmix/blob/main/model_training/preprocess/prepare_file_domain.py#L75) so that the number of chunks can represent the tokens, and this code assumes that your domain prefix is separated using -):"

What is the recommended chunk size essentially?
